services:
  web:
    container_name: django_app
    image: jabriel23/django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/opt/api_django
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - app-network

  db:
    container_name: postgres_dj
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-sb.sh
    networks:
      - app-network

  reactapp:
      container_name: react-app
      image: jabriel23/front_unilife:tag
      ports:
          - '5173:5173'
     environment:
      - REACT_APP_API_URL=http://web:8000/api  # Definindo a URL da API para o frontend React
    depends_on:
      - web
    networks:
    - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
