# Generated by Django 5.0.2 on 2024-08-25 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('cpf', models.CharField(default='', max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('ra', models.CharField(max_length=7)),
                ('id_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_django.course')),
            ],
        ),
    ]
