# Generated by Django 5.0.2 on 2024-10-11 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_django', '0003_area_organization_alter_user_ra_course_area_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_django.area'),
        ),
        migrations.AlterField(
            model_name='event',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_django.area'),
        ),
    ]
