# Generated by Django 5.0.2 on 2024-10-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_django', '0004_alter_course_area_alter_event_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ensino_medio',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
